# http://about.travis-ci.org/docs/user/build-configuration/
language: ruby

bundler_args: '--without production'

before_install:
  - "cat /etc/timezone"
  - "grep -i processor /proc/cpuinfo | wc -l"
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - "gem install bundler --pre"
  - "bundle -v"

before_script:
    - "bundle exec rake travis:before_script"

rvm:
  - 2.0.0
  - ruby-head
