development:
  host: localhost
  database: w_blog_development

test:
  host: localhost
  database: w_blog_test

# set these environment variables on your prod server
production:
  host: localhost
  database: w_blog
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
